# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: accuknox-iac@2
      inputs:
        accuknoxEndpoint: '$(accuknox-endpoint)'
        accuknoxToken: '$(accuknox-token)'
        accuknoxLabel: '$(accuknox-label)'
        inputQuiet: true
        inputCompact: true
        inputSoftFail: true
