# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: Default
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: accuknox-iac@2
      inputs:
        accuknoxEndpoint: '$(accuknox-endpoint)'
        accuknoxToken: '$(accuknox-token)'
        accuknoxLabel: '$(accuknox-label)'
        inputQuiet: true
        inputCompact: true
        inputSoftFail: true
    - task: AccuKnox-SAST@2
      inputs:
        accuknoxEndpoint: $(accuknox-endpoint)
        accuknoxToken: $(accuknox-token)
        accuknoxLabel: $(accuknox-label)
        softFail: true
    - task: accuknox-secret-scan@1
      inputs:
        accuknoxEndpoint: '$(accuknox-endpoint)'
        accuknoxToken: '$(accuknox-token)'
        accuknoxLabel: '$(accuknox-label)'
        inputSoftFail: true
    - task: accuknox-sq-sast@2
      inputs:
        sonarQubeUrl: '$(sonarQubeUrl)'
        sonarQubeToken: '$(sonarQubeToken)'
        sonarQubeProjectKey: '$(sonarQubeProjectKey)'
        accuknoxEndpoint: '$(accuknox-endpoint)'
        accuknoxToken: '$(accuknox-token)'
        accuknoxLabel: '$(accuknox-label)'
        qualityGate: false
        skipSonarQubeScan: true

    - task: AccuKnox-Container-Scan@2
      inputs:
        imageName: 'bkimminich/juice-shop'
        tag: 'latest'
        inputSoftFail: true
        accuknoxEndpoint: $(accuknox-endpoint)
        accuknoxToken: $(accuknox-token)
        accuknoxLabel: $(accuknox-label)
    - task: AccuKnox-DAST@2
      inputs:
        targetURL: 'http://testphp.vulnweb.com/'
        scanType: 'baseline'
        accuknoxEndpoint: $(accuknox-endpoint)
        accuknoxToken: $(accuknox-token)
        accuknoxLabel: $(accuknox-label)