name: AccuKnox Container Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AccuKnox Container Scanner
        uses: Vickydew1/container-scan-action@main
        with:
          # GitHub secrets
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}

          # Container image
          image_name: "nginx"       # required
          tag: "latest"             # optional, defaults to "latest"

          # Optional flags
          soft_fail: true           # workflow won't fail on scan issues
          compact: true             # hide code blocks
          quiet: true              
