name: AccuKnox Container Scan

on:
  push:
    branches: [main]

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app:latest .

      - name: Run AccuKnox Container Scanner
        uses: accuknox/container-scan-action@1.0.0
        with:
          endpoint:   ${{ secrets.ENDPOINT }}
          token:      ${{ secrets.TOKEN }}
          tenant_id:  ${{ secrets.TENANT_ID }}
          image:      "my-app"
          tag:        "latest"
          severity:   "HIGH, CRITICAL"
          label:      ${{ secrets.LABEL }}
