name: AccuKnox Container Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AccuKnox Container Scanner
        uses: Vickydew1/container-scan-action@main
        with:
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          label: ${{ secrets.ACCUKNOX_LABEL }}
          endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          image_name: "nginx"       # <-- pass container image here
          tag: "Vicky"             # optional
          severity: "CRITICAL, LOW, HIGH< MEDIUM, UNKNOWN"      # optional
          soft_fail: false          # set false to fail workflow if vulnerabilities found
