name: AccuKnox Container Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  container-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          IMAGE_NAME="my-app"
          IMAGE_TAG="latest"
          docker build -t "$IMAGE_NAME:$IMAGE_TAG" .

      - name: Run AccuKnox Container Scanner
        uses: accuknox/container-scan-action@v1.0.0
        with:
          endpoint:   ${{ secrets.ENDPOINT }}
          token:      ${{ secrets.TOKEN }}
          tenant_id:  ${{ secrets.TENANT_ID }}
          label:      ${{ secrets.LABEL }}
          image:      "my-app"
          tag:        "latest"
          severity:   "HIGH,CRITICAL"
