name: AccuKnox DAST Scan Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox DAST Scan
        uses: Vickydew1/dast-scan-action@main
        with:
          target_url: "http://testphp.vulnweb.com"   # Example vulnerable site
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          tenant_id: ${{ secrets.TENANT_ID }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          label: "my-dast-scan"
          severity_threshold: "HIGH"    # LOW / MEDIUM / HIGH
          scan_type: "baseline"         # baseline or full-scan

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: dast-report.json
