name: AccuKnox DAST Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run AccuKnox DAST Scanner
        uses: Vickydew1/dast-scan-action@main
        with:
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          label: ${{ secrets.ACCUKNOX_LABEL }}
          
          # Required
          target_url: "http://testphp.vulnweb.com"
          
          # Optional arguments for testing all features
          severity_threshold: "LOW, MEDIUM, HIGH"         # LOW, MEDIUM, HIGH
          scan_type: "full-scan"           # baseline or full-scan
          soft_fail: true
