name: AccuKnox IaC Scan Workflow - Full Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-iac-scan-options:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IaC scan with all optional flags
        uses: accuknox/iac-scan-action@v0.0.1
        with:
          directory: "./iac"
          compact: true
          quiet: true
          output_format: json
          output_file_path: "results.json"
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}

          # Optional inputs to test
          soft_fail: true
          framework: Terraform
          baseline: "./baseline.json"

      - name: Check output file
        run: cat results.json || echo "❌ No results.json file found"

      - name: List files
        run: ls -la
