name: AccuKnox IaC Scan Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v0.0.1
        with:
          directory: "./iac"                   # 👈 point to the correct folder
          compact: true
          quiet: true
          output_format: json
          output_file_path: "results.json"
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}

      - name: Debug files
        run: ls -la

      # - name: Patch results with metadata
      #   run: |
      #     if [ -f results.json ]; then
      #       echo "✅ Found results.json. Patching..."
      #       jq --arg repoLink "https://github.com/Vickydew1/Accu" \
      #          --arg branch "main" \
      #          '. += [{"details": {"repo": $repoLink, "branch": $branch}}]' \
      #          results.json > temp.json && mv temp.json results.json
      #     else
      #       echo "⚠️ results.json not found — skipping patch step"
      #     fi
