name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox IaC Scan
        uses: Vickydew1/iac-scan-action@main
        with:
          directory: "."
          soft_fail: false
          token: ${{ secrets.TOKEN }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}

          # Optional: override scan image
          # scan_image: "public.ecr.aws/k9v9d5v2/accuknox-aspm-scanner:v0.9.2"
