name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run IaC scan
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            public.ecr.aws/k9v9d5v2/accuknox-aspm-scanner:v0.13.4 \
            --directory /workspace \
            --soft_fail true \
            --endpoint cspm.demo.accuknox.com \
            --token ${{ secrets.TOKEN }} \
            --tenant_id ${{ secrets.TENANT_ID }} \
            --label ${{ secrets.LABEL }}
