name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run AccuKnox IaC Scan
        uses: Vickydew1/iac-scan-action@main
        with:
          directory: "."                     # Scan the full repo directory
          soft_fail: false                   # Fail the workflow if scan finds issues
          endpoint: ${{ secrets.ENDPOINT }} # CSPM panel URL
          label: ${{ secrets.LABEL }}       # Label to associate scan results
          token: ${{ secrets.TOKEN }}
    
