name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run IaC scan
        uses: Vickydew1/iac-scan-action@main
        with:
          directory: "."             # Directory to scan
          compact: true              # Minimize output
          quiet: true                # Show only failed checks
          output_format: json        # Format of output
          output_file_path: "results.json"  # Write results directly here
          token: ${{ secrets.TOKEN }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}
