name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v1.0.0
        with:
          directory: "."
          compact: true
          quiet: true
          soft_fail: false
          endpoint: ${{ secrets.ENDPOINT }}
          token: ${{ secrets.TOKEN }}
          label: ${{ secrets.LABEL }}
