name: accuknox iac scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  iac_scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run accuknox iac scan
        uses: Vickydew1/iac-scan-action@main
        with:
          accuknox_token: ${{ secrets.accuknox_token }}
          accuknox_label: ${{ secrets.accuknox_label }}
          accuknox_endpoint: ${{ secrets.accuknox_endpoint }}
          directory: "."      # optional
          file: ""            # optional
          compact: true       # optional
          quiet: true         # optional
          soft_fail: false    # optional
          framework: ""       # optional
