name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox IaC Scan
        uses: Vickydew1/iac-scan-action@main
        with:
          directory: "."                      
          soft_fail: true                   # <-- Enable soft fail
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          label: ${{ secrets.ACCUKNOX_LABEL }}
          file: ""                            
          compact: true                        
          quiet: true                          
          framework: ""                        
          skip_framework: ""                   
          baseline: "baseline"                 


