name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Create results folder
        run: mkdir -p results
      
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run IaC scan
        uses: Vickydew1/iac-scan-action@main
        with:
          directory: "." # Optional: Directory to scan
          compact: true  # Optional: Minimise output
          quiet: true    # Optional: Show only failed checks
          output_format: json  # Optional: Format of output
          output_file_path: "results/results_json.json"
          token: ${{ secrets.TOKEN }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}
