name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iac-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run AccuKnox IaC Scan
        uses: Vickydew1/iac-scan-action@main
        with:
          # Specify a single file to scan (optional)
          # file: "path/to/file.tf"

          # Directory to scan (default is ".")
          directory: "."

          # Compact output
          compact: true

          # Show only failed checks
          quiet: true

          # Soft fail or fail workflow on scan errors
          soft_fail: false

          # Optional: framework to scan (Terraform/Kubernetes)
          # framework: "Terraform"

          # Optional: framework to skip
          # skip_framework: "Kubernetes"

          # Authentication to AccuKnox SaaS
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          endpoint: ${{ secrets.ENDPOINT }}
          label: ${{ secrets.LABEL }}

          # Optional: override scan image
          # scan_image: "public.ecr.aws/k9v9d5v2/accuknox-aspm-scanner:v0.9.2"
