name: AccuKnox IaC Scan Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run IaC scan
        uses: public.ecr.aws/k9v9d5v2/accuknox-aspm-scanner:v0.13.4
        with:
          file:
          directory: ".".
          soft_fail: true
          endpoint: cspm.demo.accuknox.com
          baseline:
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          label: ${{ secrets.LABEL }}
