name: "AccuKnox SAST Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run SAST Scan with AccuKnox
        uses: accuknox/sast-scan-opengrep-action@v1.0.1
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true
