name: "AccuKnox SQ-SAST Scan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sq-sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run AccuKnox SQ-SAST Scan
        uses: Vickydew1/sast-scan-action@main
        with:
          skip_sonar_scan: false
          sonar_project_key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          sonar_organization_id: ${{ secrets.SONAR_ORG_ID }}
          repository_url: ${{ github.repository }}
          commit_sha: ${{ github.sha }}
          commit_ref: ${{ github.ref_name || github.ref }}
          pipeline_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          ACCUKNOX_ENDPOINT: ${{ secrets.ACCUKNOX_ENDPOINT }}
          ACCUKNOX_TOKEN: ${{ secrets.ACCUKNOX_TOKEN }}
          ACCUKNOX_LABEL: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true
